# -*- coding: utf-8 -*-
"""Indian Food Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11ltEN6JgWCLI-TVvIWd6rXf0DHSywMdR

## EDA on Indian Food Analysi ##
Source: Kaggle Datasets(Indian Dishes)
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import plotly.express as px
from plotly.offline import init_notebook_mode
import matplotlib.pyplot as plt
# %matplotlib inline

data=pd.read_csv("/indian_food.csv")

data.head()

data.columns

data.shape

data.info()

data.describe()

data.head(20)

"""## Replacing Unknown values with NaN values"""

data=data.replace(-1,np.nan)
data=data.replace('-1',np.nan)

data.head(20)

data.isnull().sum()

"""## Finding Proportions of Vegetarians and Non_vegetarian Dishes"""

pie_data=data.diet.value_counts().reset_index()

pie_data.columns=['diet','count']

import plotly.express as px

fig=px.pie(pie_data,values='count',names='diet',title='Proportion of Vegetarians and Non-Vegetarian Dishes',color_discrete_sequence=['green','red'])
fig.show()

"""## Cooking Time taken for Different indian dishes"""

cooking_time=data[['cook_time','name']]

cooking_time.head(20)

cooking_time=cooking_time.sort_values(['cook_time'],ascending=True)

ten_cook_quickly=cooking_time.head(10)

cook_data=ten_cook_quickly.cook_time.value_counts().reset_index()

cook_data.columns=['cook_time','name']
fig=px.bar(ten_cook_quickly,x='cook_time',y='name',title='dishes based on cooking time',color_discrete_sequence=['green'])
fig.show()

"""## Longest Cooking_time taken dishes"""

cooking_time_longest=cooking_time.sort_values(['cook_time'],ascending=False)

tencooking_time_longest=cooking_time_longest.head(10)

y=tencooking_time_longest['cook_time']
x=tencooking_time_longest['name']
plt.plot(x,y)
plt.title('dishes based on cooking time')
plt.show()



